// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcDNdUOiXkMqiA8-ui2BxnZWZ6TN7jGgw',
    appId: '1:316108507866:web:81808821c05b121a03b3e3',
    messagingSenderId: '316108507866',
    projectId: 'e-commerce-26-6fc37',
    authDomain: 'e-commerce-26-6fc37.firebaseapp.com',
    storageBucket: 'e-commerce-26-6fc37.firebasestorage.app',
    measurementId: 'G-WGVQ3PPFW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGjlHR62J3F6pa4B7s8fK8imEGU4S3m6A',
    appId: '1:316108507866:android:0c7283c9db25cd7203b3e3',
    messagingSenderId: '316108507866',
    projectId: 'e-commerce-26-6fc37',
    storageBucket: 'e-commerce-26-6fc37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9OAifMsiuEotiCVoJUq4krU7LlCnwoXw',
    appId: '1:316108507866:ios:00c5b8c82776709a03b3e3',
    messagingSenderId: '316108507866',
    projectId: 'e-commerce-26-6fc37',
    storageBucket: 'e-commerce-26-6fc37.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppApi26',
  );
}
